### ISSUE TITLE
Optionally prefix / suffix on :Twrite

### ISSUE THREAD

**Issue by devth** [tpope/vim-tbone#12]
Scala's REPL has a raw paste mode, activated by `:paste -raw`, which happens to be the only way you can define packages in it. I wonder if a prefix (e.g. `:paste -raw^M`) and suffix (`^D` to exit :paste mode) could be setup for this case? Even better if I can use vim-projectionist to set these up for all Scala files.

**Comment by justinmk** [comment]
seems like a custom command would be more appropriate.

**Comment by tpope** [comment]
There is a global, `g:tbone_write_initialization`, for it, but yeah, I'm inclined to agree wrapping it up as a separate function.

**Comment by devth** [comment]
Finally got around to trying this out, but @justinmk's custom command example doesn't seem to work. It errors with `Can't find pane :paste -raw^M^D`. Ideas?

**Comment by dhruvasagar** [comment]
you'd have to use ^V^M to type them literally in vim, same should apply to ^D
