### ISSUE TITLE
Unexpected behavior when running command

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-tbone#13]
For example doing the following:

`:Tmux split-window "ls"` yields a split without any of the output from `ls`.

This is strange to me because `$ tmux split-window "ls"` indeed yields the output. (only briefly however unless you do "ls; read"`)

Is there a reason why this is different?

**Comment by tpope** [comment]
Double quote is likely being interpreted as a comment.

**Comment by rgrinberg** [comment]
You're totally right. `Tmux split-window 'ls; read'` works exactly the same.
