### ISSUE TITLE
Confused about autocmd in plugin/tbone.vim

### ISSUE THREAD

**Issue by benknoble** [tpope/vim-tbone#16]
There is an autocmd in plugin/tbone.vim that has been there since the very first commit that confuses me a bit.

The plugin script sets up a command name `Tmux`. The autocmd does the same thing at `VimEnter` event: save command name, same definition, &c.

It seems redundant to me; is there something I'm missing?

**Comment by tpope** [comment]
It was to override an identically named command from some other plugin, which I believe I felt confident doing because it was strictly inferior.
