### ISSUE TITLE
Twrite for a visual selection adds a linefeed unnecessarily

### ISSUE THREAD

**Issue by Kynde** [tpope/vim-tbone#17]
Steps to repeat:
- select a part of a line which does not reach in the end of the line
- Twrite that onto some other pane

Expeted results:
- that pane receives the visual selection and nothing else

Actual results:
- that pane receives the visual selection and a line feed

It seems intentional, yet wrong. If the eol is included I get it, but not when the selection is short of that. If I go into selection with V it's fine, but not with v.

**Comment by tpope** [comment]
This is just how Vim works. `:'<,'>` is always linewise, no matter what visual mode you were in.
