### ISSUE TITLE
Feature request: support for the kitty terminal

### ISSUE THREAD

**Issue by devth** [tpope/vim-tbone#23]
[Kitty](https://sw.kovidgoyal.net/kitty/index.html) supports tabs and windows similar to tmux. I am using it as a tmux replacement for performance reasons.

Kitty has expressive [remote controls to control any tab or window](https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-send-text).

I tried to hack something on top of `vim-dispatch` that acts like `vim-tbone`:

```vimscript
function! TerminalH()
  let line=getline('.')
  execute "Spawn! kitty @ send-text --match title:left ".line."\r"
endfunction
nnoremap <leader>twh :call TerminalH()<cr>
```

It's gross and doesn't work that well when I have multiple tabs each with multiple windows.

**Comment by tpope** [comment]
A plugin designed from the ground up to abstract over both forms of multiplexing sounds very cool. Even if you ignore `:Tmux`, I don't think retrofitting all tbone functionality to support both targets is tenable.
