### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by leonardorame** [tpope/vim-tbone#24]
Hi @tpope, I just write to say Thank You! for this plugin. 

My usual workflow consists of opening a terminal with tmux, with two panes, on the left one vim instance with local code, on the right an ssh session also with vim. In my .vimrc I have line numbers enabled (`:set nu`), so until today before copying with tmux (`ctrl+b [`) I had to `:set nu!`, copy, then move to the other pane and paste (`ctrl+b ]`), this also had a problem with long text spanning many lines (tmux adds newlines that had to be removed after pasting). 

Now it's just a matter of selecting with vim, `:Tyank` and paste with `ctrl+b ]` on the desired Tmux pane.

**Comment by tpope** [comment]
Thanks :)
